"""Added status types in job_applications

Revision ID: 3edecbf64a36
Revises: c3d7d2b7d9c4
Create Date: 2026-05-28 10:20:35.198125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edecbf64a36'
down_revision: Union[str, Sequence[str], None] = 'c3d7d2b7d9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # op.drop_index(op.f('document_chunks_embedding_idx'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.drop_index(op.f('idx_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.drop_index(op.f('idx_search_vector'), table_name='document_chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('document_chunks_embedding_idx'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
