"""create first alembic

Revision ID: efd623a20b30
Revises: 
Create Date: 2026-05-22 11:41:49.842379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efd623a20b30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('documents', 'original_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('uploaded', 'processing', 'indexed', 'failed', name='document_status'),
               nullable=False,
               existing_server_default=sa.text("'uploaded'::document_status"))
    op.alter_column('documents', 'document_type',
               existing_type=postgresql.ENUM('policy', 'resume', name='document_type'),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_index(op.f('idx_job_applications_job_opening_id'), table_name='job_applications')
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_opening_id'), 'job_applications', ['job_opening_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_by'), 'tasks', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_department_id'), 'tasks', ['department_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_department_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_by'), table_name='tasks')
    op.drop_index(op.f('ix_job_applications_job_opening_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.create_index(op.f('idx_job_applications_job_opening_id'), 'job_applications', ['job_opening_id'], unique=False)
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'document_type',
               existing_type=postgresql.ENUM('policy', 'resume', name='document_type'),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('uploaded', 'processing', 'indexed', 'failed', name='document_status'),
               nullable=True,
               existing_server_default=sa.text("'uploaded'::document_status"))
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('documents', 'original_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###
